name: Generate terraform-docs
on:
  push:
    paths:
      - '*.tf'
  workflow_dispatch:

permissions:
  contents: write  # needed to push the commit

jobs:
  generate-terraform-docs:
    name: "Generate terraform-docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: terraform-docs/gh-actions@v1.4.1
        with:
          output-file: README.md
          output-method: inject
          working-dir: .

      # Needed to avoid permission errors in the next step
      - name: Fix file ownership
        run: sudo chown -R $USER:$USER .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        with:
          commit_message: "docs: update terraform-docs in README"
          file_pattern: README.md
